// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartActions from "./islands/AddToCartActions.tsx";
import * as $AddToCartButton from "./islands/AddToCartButton.tsx";
import * as $BlueTagProduct from "./islands/BlueTagProduct.tsx";
import * as $BlueTagVisit from "./islands/BlueTagVisit.tsx";
import * as $Debug from "./islands/Debug.tsx";
import * as $DescriptionCard from "./islands/DescriptionCard.tsx";
import * as $HeaderButton from "./islands/HeaderButton.tsx";
import * as $HeaderModals from "./islands/HeaderModals.tsx";
import * as $HeaderModalsV2 from "./islands/HeaderModalsV2.tsx";
import * as $HeaderSearchbar from "./islands/HeaderSearchbar.tsx";
<<<<<<< HEAD
import * as $NewAddToCartButton from "./islands/NewAddToCartButton.tsx";
=======
>>>>>>> ca0fe87ca1c5b23298866f55e7d754fb292f6cb6
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NewsletterModal from "./islands/NewsletterModal.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductAsideInfo from "./islands/ProductAsideInfo.tsx";
import * as $ProductDetailsImages from "./islands/ProductDetailsImages.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SearchNotFound from "./islands/SearchNotFound.tsx";
import * as $Searchbar from "./islands/Searchbar.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShopTogetherContainer from "./islands/ShopTogetherContainer.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Sort from "./islands/Sort.tsx";
import * as $UserButtons from "./islands/UserButtons.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartActions.tsx": $AddToCartActions,
    "./islands/AddToCartButton.tsx": $AddToCartButton,
    "./islands/BlueTagProduct.tsx": $BlueTagProduct,
    "./islands/BlueTagVisit.tsx": $BlueTagVisit,
    "./islands/Debug.tsx": $Debug,
    "./islands/DescriptionCard.tsx": $DescriptionCard,
    "./islands/HeaderButton.tsx": $HeaderButton,
    "./islands/HeaderModals.tsx": $HeaderModals,
    "./islands/HeaderModalsV2.tsx": $HeaderModalsV2,
    "./islands/HeaderSearchbar.tsx": $HeaderSearchbar,
<<<<<<< HEAD
    "./islands/NewAddToCartButton.tsx": $NewAddToCartButton,
=======
>>>>>>> ca0fe87ca1c5b23298866f55e7d754fb292f6cb6
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NewsletterModal.tsx": $NewsletterModal,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductAsideInfo.tsx": $ProductAsideInfo,
    "./islands/ProductDetailsImages.tsx": $ProductDetailsImages,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SearchNotFound.tsx": $SearchNotFound,
    "./islands/Searchbar.tsx": $Searchbar,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShopTogetherContainer.tsx": $ShopTogetherContainer,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Sort.tsx": $Sort,
    "./islands/UserButtons.tsx": $UserButtons,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
