// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlueTags/BlueTagVisit.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryBreadcrumb.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryText.tsx";
import * as $$$$$$5 from "./sections/Container.tsx";
import * as $$$$$$6 from "./sections/Content/Benefits.tsx";
import * as $$$$$$7 from "./sections/Content/CopyRight.tsx";
import * as $$$$$$8 from "./sections/Content/CustomBefefits.tsx";
import * as $$$$$$9 from "./sections/Content/CustomImageGallery.tsx";
import * as $$$$$$10 from "./sections/Content/Faq.tsx";
import * as $$$$$$11 from "./sections/Content/InfoCard.tsx";
import * as $$$$$$12 from "./sections/Content/InfoCardSeo.tsx";
import * as $$$$$$13 from "./sections/Content/Logos.tsx";
import * as $$$$$$14 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$15 from "./sections/DesignSystem/DesignSystem.tsx";
import * as $$$$$$16 from "./sections/Footer/Footer.tsx";
import * as $$$$$$17 from "./sections/Header/HeaderLayout.tsx";
import * as $$$$$$18 from "./sections/Header/HeaderLayoutV2.tsx";
import * as $$$$$$19 from "./sections/Header/HeaderNavMenu.tsx";
import * as $$$$$$20 from "./sections/Header/HeaderNavMenuV2.tsx";
import * as $$$$$$21 from "./sections/Header/TopNavBar.tsx";
import * as $$$$$$22 from "./sections/HeaderFloating.tsx";
import * as $$$$$$23 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$24 from "./sections/Images/Carousel.tsx";
import * as $$$$$$25 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$26 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$27 from "./sections/Institutional/AccordionsContent.tsx";
import * as $$$$$$28 from "./sections/Institutional/AsideMenu.tsx";
import * as $$$$$$29 from "./sections/Institutional/CardsContent.tsx";
import * as $$$$$$30 from "./sections/Institutional/ContactForm.tsx";
import * as $$$$$$31 from "./sections/Institutional/InstitutionalPage.tsx";
import * as $$$$$$32 from "./sections/Institutional/TextContent.tsx";
import * as $$$$$$33 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$34 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$35 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$36 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$37 from "./sections/Miscellaneous/NotFound.tsx";
import * as $$$$$$38 from "./sections/Miscellaneous/ProxyIframe.tsx";
import * as $$$$$$39 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$40 from "./sections/Newsletter/NewsletterModal.tsx";
import * as $$$$$$41 from "./sections/Product/ProductAdvancedDetails.tsx";
import * as $$$$$$42 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$43 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$44 from "./sections/Product/SearchNotFound.tsx";
import * as $$$$$$45 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$46 from "./sections/Product/ShopTogether.tsx";
import * as $$$$$$47 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$48 from "./sections/Seo/SeoHomeCustom.tsx";
import * as $$$$$$49 from "./sections/Seo/SeoPDPCustom.tsx";
import * as $$$$$$50 from "./sections/Seo/SeoPLPCustom.tsx";
import * as $$$$$$51 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$52 from "./sections/Social/WhatsApp.tsx";

const manifest = {
  "sections": {
    "site/sections/BlueTags/BlueTagVisit.tsx": $$$$$$0,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$1,
    "site/sections/Category/CategoryBreadcrumb.tsx": $$$$$$2,
    "site/sections/Category/CategoryList.tsx": $$$$$$3,
    "site/sections/Category/CategoryText.tsx": $$$$$$4,
    "site/sections/Container.tsx": $$$$$$5,
    "site/sections/Content/Benefits.tsx": $$$$$$6,
    "site/sections/Content/CopyRight.tsx": $$$$$$7,
    "site/sections/Content/CustomBefefits.tsx": $$$$$$8,
    "site/sections/Content/CustomImageGallery.tsx": $$$$$$9,
    "site/sections/Content/Faq.tsx": $$$$$$10,
    "site/sections/Content/InfoCard.tsx": $$$$$$11,
    "site/sections/Content/InfoCardSeo.tsx": $$$$$$12,
    "site/sections/Content/Logos.tsx": $$$$$$13,
    "site/sections/Content/Testimonials.tsx": $$$$$$14,
    "site/sections/DesignSystem/DesignSystem.tsx": $$$$$$15,
    "site/sections/Footer/Footer.tsx": $$$$$$16,
    "site/sections/Header/HeaderLayout.tsx": $$$$$$17,
    "site/sections/Header/HeaderLayoutV2.tsx": $$$$$$18,
    "site/sections/Header/HeaderNavMenu.tsx": $$$$$$19,
    "site/sections/Header/HeaderNavMenuV2.tsx": $$$$$$20,
    "site/sections/Header/TopNavBar.tsx": $$$$$$21,
    "site/sections/HeaderFloating.tsx": $$$$$$22,
    "site/sections/Images/BannerGrid.tsx": $$$$$$23,
    "site/sections/Images/Carousel.tsx": $$$$$$24,
    "site/sections/Images/ImageGallery.tsx": $$$$$$25,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$26,
    "site/sections/Institutional/AccordionsContent.tsx": $$$$$$27,
    "site/sections/Institutional/AsideMenu.tsx": $$$$$$28,
    "site/sections/Institutional/CardsContent.tsx": $$$$$$29,
    "site/sections/Institutional/ContactForm.tsx": $$$$$$30,
    "site/sections/Institutional/InstitutionalPage.tsx": $$$$$$31,
    "site/sections/Institutional/TextContent.tsx": $$$$$$32,
    "site/sections/Links/LinkTree.tsx": $$$$$$33,
    "site/sections/Links/Shortcuts.tsx": $$$$$$34,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$35,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$36,
    "site/sections/Miscellaneous/NotFound.tsx": $$$$$$37,
    "site/sections/Miscellaneous/ProxyIframe.tsx": $$$$$$38,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$39,
    "site/sections/Newsletter/NewsletterModal.tsx": $$$$$$40,
    "site/sections/Product/ProductAdvancedDetails.tsx": $$$$$$41,
    "site/sections/Product/ProductDetails.tsx": $$$$$$42,
    "site/sections/Product/ProductShelf.tsx": $$$$$$43,
    "site/sections/Product/SearchNotFound.tsx": $$$$$$44,
    "site/sections/Product/SearchResult.tsx": $$$$$$45,
    "site/sections/Product/ShopTogether.tsx": $$$$$$46,
    "site/sections/Product/Wishlist.tsx": $$$$$$47,
    "site/sections/Seo/SeoHomeCustom.tsx": $$$$$$48,
    "site/sections/Seo/SeoPDPCustom.tsx": $$$$$$49,
    "site/sections/Seo/SeoPLPCustom.tsx": $$$$$$50,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$51,
    "site/sections/Social/WhatsApp.tsx": $$$$$$52,
  },
  "apps": {
    "site/apps/deco/records.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
